config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/", to: "welcome#index"

  # Authentication routes
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#auth_failed", as: :auth_failed, via: [:get, :post]
  match "/login", to: "sessions#new", as: :login, via: :get
  match "/logout", to: "sessions#destroy", as: :logout, via: :all

  # About
  match "/about", to: "welcome#about", via: :get, as: "about"

  # Collections
  resources :collections, except: :edit do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/about", to: "collections#show_about", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/access", to: "collections#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/all-files", to: "collections#all_files", via: :get
    match "/bury", to: "collections#bury", via: :post
    match "/exhume", to: "collections#exhume", via: :post
    match "/items", to: "collections#show_items", via: :get
    match "/review-submissions", to: "collections#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "collections#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "collections#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }

    match "/children", to: "collections#children", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "collections#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "collections#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-collection-membership",
          to: "collections#edit_collection_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "collections#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-groups", to: "collections#edit_submitting_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-users", to: "collections#edit_submitting_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-unit-membership", to: "collections#edit_unit_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-results", to: "collections#item_results", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-download-counts", to: "collections#item_download_counts", via: :get
    match "/statistics-by-range", to: "collections#statistics_by_range", via: :get
    match "/submit", to: "submissions#new", via: :get
  end

  # Contact form
  match "/contact", to: "welcome#contact", via: :post,
        constraints: lambda { |request| request.xhr? }

  # Credentials
  resources :credentials, only: [:update] do
    match "/edit-password", to: "credentials#edit_password", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/register", to: "credentials#register", via: :get
    match "/reset-password", to: "credentials#new_password", via: :get
    match "/reset-password", to: "credentials#reset_password", via: [:patch, :post]
    match "/update-password", to: "credentials#update_password", via: [:patch, :post],
          constraints: lambda { |request| request.xhr? }
  end

  # Theme route
  match "/custom-styles", to: "stylesheets#show", via: :get

  # Downloads
  resources :downloads, only: :show, param: :key do
    match "/file", to: "downloads#file", via: :get, as: "file"
  end

  # Element Namespaces
  resources :element_namespaces, path: "element-namespaces", except: :show

  # Events
  match "/all-events", to: "events#index_all", via: :get, as: "all_events"
  resources :events, only: [:index, :show]

  # File Formats
  resources :file_formats, path: "file-formats", only: :index

  # Handle
  match "/handle/:prefix/:suffix", to: "handles#redirect", via: :get, as: "redirect_handle"

  # Health Check
  match "/health", to: "health#index", via: :get, as: "health"

  # Imports
  resources :imports do
    match "/complete-upload", to: "imports#complete_upload", via: :post
  end

  # Index Pages
  resources :index_pages, path: "index-pages"

  # Institutions
  resources :institutions, except: [:edit, :update], param: :key do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/access", to: "institutions#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/authentication", to: "institutions#show_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/buried-items", to: "institutions#show_buried_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/depositing", to: "institutions#show_depositing", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "institutions#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "institutions#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings/edit", to: "institutions#edit_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-agreement", to: "institutions#edit_deposit_agreement", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-help", to: "institutions#edit_deposit_help", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-questions", to: "institutions#edit_deposit_questions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-local-authentication", to: "institutions#edit_local_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-preservation", to: "institutions#edit_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "institutions#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-saml-authentication", to: "institutions#edit_saml_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-settings", to: "institutions#edit_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-theme", to: "institutions#edit_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings", to: "institutions#show_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-namespaces", to: "institutions#show_element_namespaces", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/elements", to: "institutions#show_element_registry", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/imports", to: "institutions#show_imports", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/index-pages", to: "institutions#show_index_pages", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/invitees", to: "institutions#show_invitees", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/metadata-profiles", to: "institutions#show_metadata_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/prebuilt-searches", to: "institutions#show_prebuilt_searches", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/preservation", to: "institutions#show_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/private-items", to: "institutions#show_private_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/properties", to: "institutions#show_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/rejected-items", to: "institutions#show_rejected_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/review-submissions", to: "institutions#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/settings", to: "institutions#show_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "institutions#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submission-profiles", to: "institutions#show_submission_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "institutions#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/supply-saml-configuration", to: "institutions#supply_saml_configuration", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/theme", to: "institutions#show_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/units", to: "institutions#show_units", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/usage", to: "institutions#show_usage", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/users", to: "institutions#show_users", via: :get,
          constraints: lambda { |request| request.xhr? }

app/helpers/collections_helper.rb
# frozen_string_literal: true

module CollectionsHelper

  ##
  # @param unit [Unit]                  Parent unit.
  # @param include_blank [Boolean]      Whether to include a blank entry at the
  #                                     top, typically for root units.
  # @param parent_collection [Unit]     Not part of the public contract--ignore.
  # @param options [Enumerable<String>] Not part of the public contract--ignore.
  # @param level [Integer]              Not part of the public contract--ignore.
  # @return [Enumerable<String>]        Array of options for passing to
  #                                     {options_for_select}.
  #
  def collection_tree_options(unit: nil,
                              include_blank: false,
                              parent_collection: nil,
                              options: [],
                              level: 0)
    if include_blank && level == 0
      options << [ "None (Root Level)", nil ]
    end
    collections = Collection.search.
        institution(current_institution).
        order("#{Collection::IndexFields::TITLE}.sort").
        limit(999)
    if unit
      collections.primary_unit(unit)
    end
    if parent_collection
      collections.parent_collection(parent_collection)
    else
      collections.include_children(false)
    end
    collections.each do |collection|
      indent = "&nbsp;&nbsp;&nbsp;&nbsp;" * level
      arrow  = (level > 0) ? raw("&#8627; ") : ""
      options << [raw("#{indent}#{arrow}#{collection.title}"), collection.id]
      collection_tree_options(unit: unit,
                              include_blank: false,
                              parent_collection: collection,
                              options: options,
                              level: level + 1)
    end
    options
  end

end

app/views/collections/_access_form.html.haml
-# frozen_string_literal: true
-#
-# Required arguments:
-#
-# collection [Collection]
-#
= form_for(collection, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  -# `collection` is required in the params (but this attribute is not permitted)
  = f.hidden_field :id, value: f.object.id

  .form-group
    %h5 Managers
    - user_strings = f.object.managing_users.each.map(&:to_autocomplete)
    - user_strings << "" if user_strings.empty?
    - user_strings.each do |user_str|
      .input-group.mb-3.user
        = text_field_tag "managers[]", user_str,
                         autocomplete: "off",
                         class: "form-control"
        .input-group-append
          %button.btn.btn-sm.btn-outline-danger.remove{type: "button"}
            %i.fa.fa-minus
            Remove
        .dropdown-menu
          - # populated by javascript
    %button.btn.btn-sm.btn-outline-success.add
      %i.fa.fa-plus
      Add Submitter

  %hr

  .form-group
    %h5 Submitters
    - user_strings = f.object.submitting_users.each.map(&:to_autocomplete)
    - user_strings << "" if user_strings.empty?
    - user_strings.each do |user_str|
      .input-group.mb-3.user
        = text_field_tag "submitters[]", user_str,
                         autocomplete: "off",
                         class: "form-control"
        .input-group-append
          %button.btn.btn-sm.btn-outline-danger.remove{type: "button"}
            %i.fa.fa-minus
            Remove
        .dropdown-menu
          - # populated by javascript
    %button.btn.btn-sm.btn-outline-success.add
      %i.fa.fa-plus
      Add Submitter

  .clearfix
    .float-right
      %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
      = f.submit("Edit", class: "btn btn-primary")

app/views/collections/_administering_groups_form.html.haml
-# frozen_string_literal: true
-#
-# Required locals:
-#
-# collection [Collection]
-#
= form_for(collection, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  -# `collection` is required in the params (but not permitted)
  = f.hidden_field :id, value: f.object.id

  = hidden_field_tag "administering_user_group_ids[]"
  - UserGroup.where(institution: collection.institution).order(:name).each do |user_group|
    .form-check
      = check_box_tag "administering_user_group_ids[]", user_group.id,
                      f.object.administrator_groups.where(user_group: user_group).any?,
                      { id: "administering_user_group_ids_#{user_group.id}", class: "form-check-input" }
      = label_tag "administering_user_group_ids_#{user_group.id}",
        user_group.name, class: "form-check-label"

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/collections/_membership_form.html.haml
-# frozen_string_literal: true
//
// Required arguments:
//
// collection [Collection]
// primary_unit [Unit]

- options = unit_tree_options

= form_for(collection, remote: true) do |f|
  .error-messages
    - # populated via ajax by shared/_validation_messages.js.erb

  .form-group
    = f.label :primary_unit_id, "Primary Unit"
    = f.select(:primary_unit_id,
        options_for_select(options, primary_unit.id),
        {}, class: 'custom-select')

  .form-group
    = f.label :units, "Other Units"
    - units = f.object.units.order(:title).to_a.dup
    - units << Unit.new if units.empty?
    - units.each do |unit|
      .input-group.mb-3
        = select_tag "collection[unit_ids][]",
                     options_for_select(options, unit.id),
                     class: "custom-select"
        .input-group-append
          %button.btn.btn-outline-danger.remove{type: "button"}
            %i.fa.fa-minus
            Remove
    %button.btn.btn-sm.btn-outline-success.add
      %i.fa.fa-plus
      Add Other Unit

  .clearfix
    .float-right
      %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
      = f.submit("Change", class: "btn btn-primary")

app/views/collections/_properties_form.html.haml
-# frozen_string_literal: true
-#
-# Required arguments:
-#
-# collection [Collection]
-#
= form_for(collection, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  -# Include this only because `collection` is required in the params.
  = f.hidden_field :id, value: f.object.id

  .mb-3
    = f.label :title, class: "required"
    = f.text_field :title, class: "form-control"

  .mb-3
    = f.label :description
    = f.text_area :description, class: "form-control"

  .mb-3
    = f.label :short_description, "Short Description"
    = f.text_area :short_description, class: "form-control"

  .mb-3
    = f.label :introduction
    = f.text_area :introduction, class: "form-control"
    %p.form-text
      = icon_for(:info)
      The following HTML tags are allowed:
      = allowed_html_tags

  .mb-3
    = f.label :rights
    = f.text_area :rights, class: "form-control"

  .mb-3
    = f.label :provenance
    = f.text_area :provenance, class: "form-control"

  .mb-3
    = f.label :metadata_profile_id, "Metadata Profile"
    = f.select :metadata_profile_id, MetadataProfile.where(institution: f.object.institution).order(:name).pluck(:name, :id),
               { include_blank: true }, class: "form-select"
    %p.form-text
      = icon_for(:info)
      If left blank, the metadata profile will be inherited from the unit, or
      else the default profile will be used.

  .mb-3
    = f.label :submission_profile_id, "Submission Profile"
    = f.select :submission_profile_id, SubmissionProfile.where(institution: f.object.institution).order(:name).pluck(:name, :id),
               { include_blank: true }, class: "form-select"
    %p.form-text
      = icon_for(:info)
      If left blank, the submission profile will be inherited from the unit, or
      else the default profile will be used.

  .mb-3
    .form-check
      = f.check_box :accepts_submissions, class: 'form-check-input'
      = f.label :accepts_submissions, "Accepts Submissions", class: "form-check-label"
    %p.form-text
      = icon_for(:info)
      When checked, new submissions are accepted, subject to authorization.
      When unchecked, new submissions are not allowed, regardless of authorization.

  .mb-3
    .form-check
      = f.check_box :submissions_reviewed, class: 'form-check-input'
      = f.label :submissions_reviewed, "Submissions Reviewed", class: "form-check-label"
    %p.form-text
      = icon_for(:info)
      When enabled, new submissions must be reviewed by a collection administrator
      before they will appear in public. Only direct collection administrators
      and direct members of user groups assigned to administer the collection
      will be notified of new submissions.
    %p.form-text
      Changing this will not affect submitted items that are still in the review queue.

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: 'btn btn-primary')

app/views/collections/_show_button_group.html.haml
- can_bury    = policy(@collection).bury?
- can_destroy = policy(@collection).destroy?
- can_exhume  = policy(@collection).exhume?

- if can_bury || can_destroy || can_exhume
  .btn-group.float-end{role: "group"}
    .dropdown
      %button.btn.btn-light.dropdown-toggle{type:             "button",
                                            "data-bs-toggle": "dropdown",
                                            "aria-expanded":  "false"}
        %i.fa.fa-ellipsis-h
        Actions
      %ul.dropdown-menu
        - if !@collection.buried && can_bury
          %li
            = link_to(collection_bury_path(@collection),
                      class:          "dropdown-item",
                      method:         :post,
                      "data-confirm": "Are you sure you want to delete this collection? This operation is reversible. If you would prefer to delete it permanently, please contact a system administrator.") do
              = icon_for(:delete)
              Delete
        - if can_destroy
          %li
            = link_to(collection_path(@collection),
                      class:          "dropdown-item",
                      method:         :delete,
                      "data-confirm": "Are you sure you want to permanently delete this collection? This cannot be undone.") do
              = icon_for(:delete)
              Delete Permanently
        - if @collection.buried? && can_exhume
          %li
            = link_to(collection_exhume_path(@collection),
                      class:          "dropdown-item",
                      method:         :post,
                      "data-confirm": "Are you sure you want to undelete this collection?") do
              %i.fa.fa-trash-restore
              Undelete

app/views/collections/_show_downloads_by_item.html.haml
-# Content for the Statistics -> Downloads By Item tab

.float-end
  = link_to(collection_item_download_counts_path(@collection,
                                                format: :csv,
                                                params: params.permit(:from_year, :from_month, :to_year, :to_month)),
                                                class: "btn btn-light") do
    = icon_for(:download)
    CSV

%table.table
  %thead
    %tr
      %th Item
      %th Downloads
  %tbody
    - @items.each do |row|
      %tr
        %td= link_to(row['title'], item_path(row['id']))
        %td= number_with_delimiter(row['dl_count'])
    %tr
      %th Total
      %th= number_with_delimiter(@items.map{ |row| row['dl_count'] }.sum)

app/views/collections/_show_downloads_tab_content.html.haml
%table.table
  %thead
    %tr
      %th Item
      %th Download Count
  %tbody
    - @items.each do |row|
      %tr
        %td= link_to(row['title'], item_path(row['id']))
        %td= number_with_delimiter(row['dl_count'])
    %tr
      %th Total
      %th= number_with_delimiter(@items.map{ |row| row['dl_count'] }.sum)

app/views/collections/_show_items_tab.html.haml
.btn-group.float-end{role: "group"}
  - if policy(@collection).submit_item?
    .btn-group{role: "group"}
      = link_to(collection_submit_path(@collection), class: "btn btn-light", role: "button") do
        %i.fas.fa-plus
        Submit Item To This Collection
  - if @items.exists? && policy(@collection).export_items?
    .btn-group{role: "group"}
      %button#export-button.btn.btn-light.dropdown-toggle{type:             "button",
                                                          "data-bs-toggle": "dropdown",
                                                          "aria-expanded":  "false"}
        = icon_for(:download)
        Export
      .dropdown-menu.dropdown-menu-right{"aria-labelledby": "export-button"}
        %button.dropdown-item.download-csv{"data-collection-id": @collection.id,
                                           "data-bs-target":     "#download-csv-modal",
                                           "data-bs-toggle":     "modal",
                                           role:                 "button"}
          All Items As CSV
        %button.dropdown-item.download-files{"data-collection-id": @collection.id,
                                             "data-bs-target":     "#download-files-modal",
                                             "data-bs-toggle":     "modal",
                                             role:                 "button"}
          All Files

.clearfix.mb-3

- if @items.count.positive?
  = form_tag(collection_path(@collection), method: :get, class: "filter") do
    = hidden_field_tag("fq[]", "#{Item::IndexFields::COLLECTION_TITLES}:#{@collection.title}")
    .card.mb-3
      .card-body
        %ul#search-tabs.nav.nav-pills.mb-0{role: "tablist"}
          %li.nav-item{role: "presentation"}
            %button#all-items-tab.nav-link.active{"data-bs-toggle": "pill",
                                                  "data-bs-target": "#all-items",
                                                  type:             "button",
                                                  role:             "tab",
                                                  "aria-controls":  "all-items",
                                                  "aria-selected":  "true"} All Items
          %li.nav-item{role: "presentation"}
            %button#simple-search-tab.nav-link{"data-bs-toggle": "pill",
                                               "data-bs-target": "#simple-search",
                                               type:             "button",
                                               role:             "tab",
                                               "aria-controls":  "simple-search",
                                               "aria-selected":  "true"} Simple Search
          %li.nav-item{role: "presentation"}
            %button#advanced-search-tab.nav-link{"data-bs-toggle": "pill",
                                                 "data-bs-target": "#advanced-search",
                                                 type:             "button",
                                                 role:             "tab",
                                                 "aria-controls":  "advanced-search",
                                                 "aria-selected":  "true"} Advanced Search
        .tab-content
          #all-items.tab-pane.fade.show.active{role:              "tabpanel",
                                               "aria-labelledby": "all-items-tab"}
            -# this tab is empty
          #simple-search.tab-pane.fade.mt-3{role: "tabpanel",
                                            "aria-labelledby": "simple-search-tab"}
            .input-group.filter-field
              = filter_field
          #advanced-search.tab-pane.fade.mt-3{role: "tabpanel",
                                              "aria-labelledby": "advanced-search-tab"}
            = advanced_search_form(@collection.effective_metadata_profile)

    .row.justify-content-between
      .col-8
      .col-4
        .input-group.mb-3
          = sort_menu(@collection.effective_metadata_profile)

  #items-xhr-content
    -# items/listing inserted here via XHR
- else
  This collection does not contain any items.

= render partial: "shared/xhr_modal",
         locals: { id:    "download-files-modal",
                   title: "Download All Files" }
= render partial: "shared/xhr_modal",
         locals: { id:    "download-csv-modal",
                   title: "Download CSV" }

app/views/collections/_show_statistics_tab.html.haml
#error-flash.alert.alert-danger{style: "display: none"}

= hidden_field_tag("chart_color", current_institution.primary_color)

.card.mb-3
  .card-body
    = form_tag("#", method: :get, class: "form-inline") do
      = date_range_picker

%ul.nav.nav-tabs{role: "tablist"}
  %li.nav-item{role: "presentation"}
    %button#statistics-by-month-tab.nav-link.active{"data-bs-toggle": "tab",
                                                    "data-bs-target": "#statistics-by-month-tab-content",
                                                    role:             "tab",
                                                    type:             "button",
                                                    "aria-controls":  "statistics-by-month-tab-content",
                                                    "aria-selected":  "true"} Statistics By Month

  %li.nav-item{role: "presentation"}
    %button#downloads-by-item-tab.nav-link{"data-bs-toggle": "tab",
                                           "data-bs-target": "#downloads-by-item-tab-content",
                                           role:             "tab",
                                           type:             "button",
                                           "aria-controls":  "downloads-by-item-tab-content",
                                           "aria-selected":  "false"} Downloads By Item

.tab-content
  #statistics-by-month-tab-content.tab-pane.fade.show.active{role: "tabpanel",
                                                             "aria-labelledby": "home-tab"}
    = spinner
  #downloads-by-item-tab-content.tab-pane.fade{role: "tabpanel",
                                               "aria-labelledby": "home-tab"}
    = spinner

app/views/collections/_show_submissions_in_progress_tab.html.haml
- if @count > 0
  - pagination = paginate(actual_count:     @count,
                          page:             @current_page,
                          per_page:         @window,
                          permitted_params: @permitted_params)

  .card.mt-3.mb-3
    #search-status.card-body.pt-3.pb-3
      = search_status(@count, @start, @window, "item")

  .row.justify-content-md-center
    .col-md-auto
      = pagination

  = submission_list(@items)

  .row.justify-content-md-center
    .col-md-auto
      = pagination

- else
  There are currently no submissions in progress.

app/views/collections/_submitting_users_form.html.haml
-# frozen_string_literal: true
-#
-# Required locals:
-#
-# collection [Collection]
-#
= form_for(collection, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  -# `collection` is required in the params (but this attribute is not permitted)
  = f.hidden_field :id, value: f.object.id

  - user_strings = f.object.submitting_users.each.map(&:to_autocomplete)
  - user_strings << "" if user_strings.empty?
  - user_strings.each do |user_str|
    .input-group.mb-3.user
      = text_field_tag "submitters[]", user_str,
                       autocomplete: "off",
                       class: "form-control"
      %button.btn.btn-sm.btn-outline-danger.remove{type: "button"}
        %i.fa.fa-minus
        Remove
      .dropdown-menu
        - # populated by javascript
  %button.btn.btn-sm.btn-outline-success.add
    %i.fa.fa-plus
    Add User

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/collections/show_buried.html.haml
- provide :body_id, "show_collection"
- provide :title, @collection.title

.btn-group.float-end{role: "group"}
  - if policy(@collection).exhume?
    = link_to(collection_exhume_path(@collection),
              class:          "btn btn-danger",
              method:         :post,
              "data-confirm": "Are you sure you want to undelete this collection?") do
      %i.fa.fa-trash-restore
      Undelete

.clearfix
.text-center
  %h1 410 Gone
  %hr
  %p This collection has been deleted.