config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/", to: "welcome#index"

  # Authentication routes
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#auth_failed", as: :auth_failed, via: [:get, :post]
  match "/login", to: "sessions#new", as: :login, via: :get
  match "/logout", to: "sessions#destroy", as: :logout, via: :all

  # About
  match "/about", to: "welcome#about", via: :get, as: "about"

  # Collections
  resources :collections, except: :edit do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/about", to: "collections#show_about", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/access", to: "collections#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/all-files", to: "collections#all_files", via: :get
    match "/bury", to: "collections#bury", via: :post
    match "/exhume", to: "collections#exhume", via: :post
    match "/items", to: "collections#show_items", via: :get
    match "/review-submissions", to: "collections#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "collections#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "collections#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }

    match "/children", to: "collections#children", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "collections#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "collections#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-collection-membership",
          to: "collections#edit_collection_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "collections#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-groups", to: "collections#edit_submitting_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-users", to: "collections#edit_submitting_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-unit-membership", to: "collections#edit_unit_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-results", to: "collections#item_results", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-download-counts", to: "collections#item_download_counts", via: :get
    match "/statistics-by-range", to: "collections#statistics_by_range", via: :get
    match "/submit", to: "submissions#new", via: :get
  end

  # Contact form
  match "/contact", to: "welcome#contact", via: :post,
        constraints: lambda { |request| request.xhr? }

  # Credentials
  resources :credentials, only: [:update] do
    match "/edit-password", to: "credentials#edit_password", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/register", to: "credentials#register", via: :get
    match "/reset-password", to: "credentials#new_password", via: :get
    match "/reset-password", to: "credentials#reset_password", via: [:patch, :post]
    match "/update-password", to: "credentials#update_password", via: [:patch, :post],
          constraints: lambda { |request| request.xhr? }
  end

  # Theme route
  match "/custom-styles", to: "stylesheets#show", via: :get

  # Downloads
  resources :downloads, only: :show, param: :key do
    match "/file", to: "downloads#file", via: :get, as: "file"
  end

  # Element Namespaces
  resources :element_namespaces, path: "element-namespaces", except: :show

  # Events
  match "/all-events", to: "events#index_all", via: :get, as: "all_events"
  resources :events, only: [:index, :show]

  # File Formats
  resources :file_formats, path: "file-formats", only: :index

  # Handle
  match "/handle/:prefix/:suffix", to: "handles#redirect", via: :get, as: "redirect_handle"

  # Health Check
  match "/health", to: "health#index", via: :get, as: "health"

  # Imports
  resources :imports do
    match "/complete-upload", to: "imports#complete_upload", via: :post
  end

  # Index Pages
  resources :index_pages, path: "index-pages"

  # Institutions
  resources :institutions, except: [:edit, :update], param: :key do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/access", to: "institutions#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/authentication", to: "institutions#show_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/buried-items", to: "institutions#show_buried_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/depositing", to: "institutions#show_depositing", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "institutions#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "institutions#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings/edit", to: "institutions#edit_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-agreement", to: "institutions#edit_deposit_agreement", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-help", to: "institutions#edit_deposit_help", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-questions", to: "institutions#edit_deposit_questions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-local-authentication", to: "institutions#edit_local_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-preservation", to: "institutions#edit_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "institutions#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-saml-authentication", to: "institutions#edit_saml_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-settings", to: "institutions#edit_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-theme", to: "institutions#edit_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings", to: "institutions#show_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-namespaces", to: "institutions#show_element_namespaces", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/elements", to: "institutions#show_element_registry", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/imports", to: "institutions#show_imports", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/index-pages", to: "institutions#show_index_pages", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/invitees", to: "institutions#show_invitees", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/metadata-profiles", to: "institutions#show_metadata_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/prebuilt-searches", to: "institutions#show_prebuilt_searches", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/preservation", to: "institutions#show_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/private-items", to: "institutions#show_private_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/properties", to: "institutions#show_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/rejected-items", to: "institutions#show_rejected_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/review-submissions", to: "institutions#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/settings", to: "institutions#show_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "institutions#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submission-profiles", to: "institutions#show_submission_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "institutions#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/supply-saml-configuration", to: "institutions#supply_saml_configuration", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/theme", to: "institutions#show_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/units", to: "institutions#show_units", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/usage", to: "institutions#show_usage", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/users", to: "institutions#show_users", via: :get,
          constraints: lambda { |request| request.xhr? }

app/models/user_group.rb
# frozen_string_literal: true

##
# Aggregation of {User}s, {AdGroup}s, and other dimensions, for the purpose of
# performing group-based authorization.
#
# User groups can be global or scoped to an institution. Global groups can only
# be created or edited by system administrators.
#
# User groups have human-readable {#name names}. They also have a {#key} that
# is unique within the same scope. The key is generally used only within the
# application to get a handle on certain {#SYSTEM_REQUIRED_GROUPS
# system-required groups}. For those groups, it is fixed and known. For other
# groups, like whatever arbitrary groups are created within an institution, it
# is auto-filled with a random string.
#
# When an {Institution} is created, a group that represents it is created along
# with it. This group is considered to {UserGroup#defines_institution define
# the institution}.
#
# # Attributes
#
# * `created_at`          Managed by ActiveRecord.
# * `defines_institution` Whether the group defines the users in its owning
#                         institution. Every institution should have one such
#                         group.
# * `institution_id`      Foreign key to {Institution} indicating that the
#                         group is exclusive to that institution. May also be
#                         `nil`, indicating that the group is global, available
#                         to all institutions.
# * `key`                 Short string identifier that is unique within an
#                         institutional scope. This is used within the
#                         application to get a handle on certain
#                         {#SYSTEM_REQUIRED_GROUPS system-required groups},
#                         and also to construct {Embargo item embargoes} within
#                         import files.
# * `name`                Arbitrary human-readable name that is unique within
#                         an institutional scope.
# * `updated_at`          Managed by ActiveRecord.
#
class UserGroup < ApplicationRecord
  include Breadcrumb

  # The key given to a user group that {#defining_institution defines its
  # institution}.
  DEFINING_INSTITUTION_KEY = "institution"
  # Key of the sysadmin group.
  SYSADMIN_KEY             = "sysadmin"
  # The application needs these groups to exist.
  SYSTEM_REQUIRED_GROUPS   = %w(sysadmin)

  belongs_to :institution, optional: true

  has_many :ad_groups
  has_many :bitstream_authorizations
  has_many :collection_administrator_groups
  has_many :departments
  has_many :email_patterns
  has_many :hosts
  has_many :submitter_groups
  has_many :unit_administrator_groups

  has_and_belongs_to_many :affiliations
  has_and_belongs_to_many :embargoes
  has_and_belongs_to_many :users

  normalizes :key, :name, with: -> (value) { value.squish }

  validates :name, presence: true # uniqueness enforced by database constraints
  validates :key, presence: true  # uniqueness enforced by database constraints
  validate :validate_sysadmin_group

  after_save :ensure_defines_institution_uniqueness
  before_destroy :prevent_destroy_of_required_group

  before_validation :ascribe_key, if: :new_record?

  ##
  # @param hostname [String]
  # @param ip [String]
  # @return [Enumerable<UserGroup>]
  # @see Host#all_matching_hostname_or_ip
  #
  def self.all_matching_hostname_or_ip(hostname, ip)
    Host.all_matching_hostname_or_ip(hostname, ip).map(&:user_group)
  end

  ##
  # @return [UserGroup] The sysadmin group.
  #
  def self.sysadmin
    UserGroup.find_by_key(SYSADMIN_KEY)
  end

  def breadcrumb_label
    name
  end

  def breadcrumb_parent
    UserGroup
  end

  ##
  # Returns whether the given user is considered to be a member of the
  # instance. Membership is determined by the following logic:
  #
  # ```
  # (is a directly associated User)
  # OR (has an email address matching one of the email patterns)
  # OR (has an IP address or hostname matching one of the host patterns)
  # OR (belongs to an associated department)
  # OR (is of an associated affiliation)
  # OR (belongs to an associated AD Group)
  # ```
  #
  # @param user [User]
  # @return [Boolean]
  #
  def includes?(user:, client_ip: nil, client_hostname: nil)
    # is a directly associated User
    self.users.find{ |u| u.id == user.id }.present? ||
    # has a matching email address
    self.email_patterns.find{ |p| p.matches?(user.email) }.present? ||
    # has a matching client IP address or hostname
    self.hosts.find{ |h| (client_ip && h.pattern_matches?(client_ip)) ||
      (client_hostname && h.pattern_matches?(client_hostname)) }.present? ||
    # belongs to an associated department
    self.departments.find{ |d| d.name == user.department&.name }.present? ||
    # is of an associated affiliation
    self.affiliations.find{ |a| a.id == user.affiliation_id }.present? ||
    # belongs to an associated AD group
    # (this check comes last because it is the most expensive)
    self.ad_groups.find{ |g| user.belongs_to_ad_group?(g) }.present?
  end

  ##
  # @return [Boolean] Whether the group is required by the system. Required
  #                   groups can be modified but not deleted.
  #
  def required?
    self.defines_institution || SYSTEM_REQUIRED_GROUPS.include?(self.key)
  end

  ##
  # @return [String]
  #
  def to_s
    self.name
  end

  private

  def ascribe_key
    if self.key.blank?
      if self.defines_institution
        self.key = DEFINING_INSTITUTION_KEY
      else
        self.key = SecureRandom.hex
      end
    end
  end

  ##
  # Marks all other instances of the same institution as "not defining the
  # institution" if the instance is marked as defining the institution.
  #
  def ensure_defines_institution_uniqueness
    if self.defines_institution
      self.class.all.
        where(institution_id: self.institution_id).
        where("id != ?", self.id).each do |instance|
        instance.update!(defines_institution: false)
      end
    end
  end

  def prevent_destroy_of_required_group
    if SYSTEM_REQUIRED_GROUPS.include?(self.key)
      errors.add(:base, :undestroyable)
      throw :abort
    end
  end

  ##
  # Ensures that there is only one group with a key of {SYSADMIN_KEY}.
  #
  def validate_sysadmin_group
    if self.key == SYSADMIN_KEY && self.institution_id.present?
      errors.add(:key, "cannot be that of the system administrator group")
    end
  end

end

app/views/user_groups/_ad_groups_form.html.haml
-# @param user_group [UserGroup]

= form_for(user_group, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .mb-3
    - names = f.object.ad_groups.order(:name).to_a
    - names << "" if names.empty?
    - names.each do |name|
      .input-group.mb-3
        = text_field_tag "user_group[ad_groups][]", name,
                         class: "form-control"
        %button.btn.btn-outline-danger.remove{type: "button"}
          %i.fa.fa-minus

  %button.btn.btn-outline-success.add{type: "button"}
    %i.fa.fa-plus

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/user_groups/_affiliations_form.html.haml
-# @param user_group [UserGroup]

= form_for(user_group, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  = hidden_field_tag "user_group[affiliation_ids][]"
  - Affiliation.all.order(:name).each do |affiliation|
    .form-check
      = check_box_tag "user_group[affiliation_ids][]", affiliation.id,
                        f.object.affiliations.include?(affiliation),
                        { id: "user_group_affiliation_ids_#{affiliation.id}", class: "form-check-input" }
      = label_tag "user_group_affiliation_ids_#{affiliation.id}",
        affiliation.name, class: "form-check-label"

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/user_groups/_departments_form.html.haml
-# @param user_group [UserGroup]

= form_for(user_group, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .alert.alert-light
    = icon_for(:info)
    = raw("Department names must match their names in the #{link_to("Campus Directory", "https://directory.illinois.edu/search")}.")

  = hidden_field_tag "user_group[departments][]"
  - departments = f.object.departments
  - departments = [Department.new] if departments.empty?
  - departments.each do |department|
    .input-group.mb-3
      = text_field_tag "user_group[departments][]", department.name,
                       class: "form-control"
      %button.btn.btn-outline-danger.remove{type: "button"}
        %i.fa.fa-minus
  %button.btn.btn-outline-success.add{type: "button"}
    %i.fa.fa-plus

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/user_groups/_email_patterns_form.html.haml
-# @param user_group [UserGroup]

= form_for(user_group, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .alert.alert-light
    = icon_for(:info)
    Surround the pattern with slashes (e.g.
    %code /@example.org/
    ) to use a regular expression. Otherwise, the pattern will be matched
    literally within an email address.

  .mb-3
    - patterns = f.object.email_patterns.order(:pattern).to_a
    - patterns << "" if patterns.empty?
    - patterns.each do |pattern|
      .input-group.mb-3
        = text_field_tag "user_group[email_patterns][]", pattern,
                         class: "form-control"
        %button.btn.btn-outline-danger.remove{type: "button"}
          %i.fa.fa-minus

  %button.btn.btn-outline-success.add{type: "button"}
    %i.fa.fa-plus

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/user_groups/show.html.haml
- provide :body_id, "show_user_group"
- provide :title, @user_group.name

- can_edit             = policy(@user_group).edit?
- show_uiuc_dimensions = @user_group.institution&.key == "uiuc" || !@user_group.institution

.btn-group.float-end{role: "group"}
  - if can_edit
    -# Edit button
    %button.btn.btn-light.edit-user-group{"data-bs-target":     "#edit-user-group-modal",
                                          "data-bs-toggle":     "modal",
                                          "data-user-group-id": @user_group.id,
                                          type:                 "button"}
      %i.fa.fa-pencil-alt
      Edit
  - if policy(@user_group).destroy?
    -# Delete button
    = link_to(user_group_path(@user_group), class: "btn btn-danger",
                                            role: "button",
                                            method: :delete,
                                            data: { confirm: "Are you sure you want to delete this user group?" }) do
      = icon_for(:delete)
      Delete

%h1
  = @user_group.name
  - unless @user_group.institution
    %small
      %span.badge.bg-primary GLOBAL

- if @user_group.defines_institution
  .alert.alert-light
    = icon_for(:info)
    This group defines all of the members of
    = "#{current_institution.name},"
    including faculty, staff, and students. When an item is submitted with the
    option for institution-only access privileges, an embargo is attached to it
    allowing access only to members of this group.

%dl
  %dt Key
  %dd
    %code= @user_group.key

%ul.nav.nav-tabs{role: "tablist"}
  %li.nav-item{role: "presentation"}
    %button#membership-tab.nav-link.active{"data-bs-toggle": "tab",
                                           "data-bs-target": "#membership",
                                           role:             "tab",
                                           type:             "button",
                                           "aria-controls":  "membership",
                                           "aria-selected":  "true"} Membership
  %li.nav-item{role: "presentation"}
    %button#usage-tab.nav-link{"data-bs-toggle": "tab",
                               "data-bs-target": "#usage",
                               role:             "tab",
                               type:             "button",
                               "aria-controls":  "usage",
                               "aria-selected":  "true"} Usage

.tab-content
  #membership.tab-pane.fade.show.active{role:              "tabpanel",
                                        "aria-labelledby": "membership-tab"}
    .row.mb-3
      .col-sm-12
        .card
          .card-body
            - if can_edit
              .float-end
                %button.btn.btn-light.btn-sm.edit-users{"data-bs-target":         "#edit-users-modal",
                                                        "data-bs-toggle":         "modal",
                                                        "data-user-group-id":     @user_group.id,
                                                        "data-user-group-global": @user_group.institution_id.blank? ? "true" : "false",
                                                        type:                     "button"}
                  %i.fa.fa-pencil-alt
                  Edit
            %h4.card-title Direct User Assignments
            - if @users.any?
              - if @user_group.institution_id
                %ul
                  - @users.each do |user|
                    %li= link_to("#{user.name} (#{user.email})", user)
              - else
                %table.table
                  - @users.each do |user|
                    %tr
                      %td
                        = link_to(user) do
                          = icon_for(user)
                          = user.name
                        = " (#{user.email})"
                      %td
                        = link_to(user.institution) do
                          = icon_for(user.institution)
                          = user.institution.name
            - else
              %p None

    .row.mb-3
      .col-sm-4
        - if show_uiuc_dimensions
          .card
            .card-body
              - if can_edit
                .float-end
                  %button.btn.btn-light.btn-sm.edit-departments{"data-bs-target":     "#edit-departments-modal",
                                                                "data-bs-toggle":     "modal",
                                                                "data-user-group-id": @user_group.id,
                                                                type:                 "button"}
                    %i.fa.fa-pencil-alt
                    Edit
              %h4.card-title
                Departments
                %small
                  %span.badge.bg-primary UIUC ONLY
              - if @departments.any?
                %ul
                  - @departments.each do |department|
                    %li= department.name
              - else
                %p None
      .col-sm-4
        - if show_uiuc_dimensions
          .card
            .card-body
              - if can_edit
                .float-end
                  %button.btn.btn-light.btn-sm.edit-affiliations{"data-bs-target":     "#edit-affiliations-modal",
                                                                 "data-bs-toggle":     "modal",
                                                                 "data-user-group-id": @user_group.id,
                                                                 type:                 "button"}
                    %i.fa.fa-pencil-alt
                    Edit
              %h4.card-title
                Affiliations
                %small
                  %span.badge.bg-primary UIUC ONLY
              - if @affiliations.any?
                %ul
                  - @affiliations.each do |affiliation|
                    %li= affiliation.name
              - else
                %p None

      .col-sm-4
        - if show_uiuc_dimensions
          .card
            .card-body
              - if can_edit
                .float-end
                  %button.btn.btn-light.btn-sm.edit-ad-groups{"data-bs-target":     "#edit-ad-groups-modal",
                                                              "data-bs-toggle":     "modal",
                                                              "data-user-group-id": @user_group.id,
                                                              type:                 "button"}
                    %i.fa.fa-pencil-alt
                    Edit
              %h4.card-title
                AD Groups
                %small
                  %span.badge.bg-primary UIUC ONLY
              - if @ad_groups.any?
                %ul
                  - @ad_groups.each do |group|
                    %li= group.name
              - else
                %p None

    .alert.alert-light
      = icon_for(:info)
      The aspects below are not stored in the system.
      The system can check a whether a particular logged-in user belongs to the
      group based on these aspects, but it cannot generate a definitive list of
      users who belong to it.

    .row.mb-3
      .col-sm-6
        .card
          .card-body
            - if can_edit
              .float-end
                %button.btn.btn-light.btn-sm.edit-hosts{"data-bs-target":     "#edit-hosts-modal",
                                                        "data-bs-toggle":     "modal",
                                                        "data-user-group-id": @user_group.id,
                                                        type:                 "button"}
                  %i.fa.fa-pencil-alt
                  Edit
            %h4.card-title Hosts
            - if @hosts.any?
              %ul
                - @hosts.each do |group|
                  %li
                    %code= group.pattern
            - else
              %p None
      .col-sm-6
        .card
          .card-body
            - if can_edit
              .float-end
                %button.btn.btn-light.btn-sm.edit-email-patterns{"data-bs-target":     "#edit-email-patterns-modal",
                                                                 "data-bs-toggle":     "modal",
                                                                 "data-user-group-id": @user_group.id,
                                                                 type:                 "button"}
                  %i.fa.fa-pencil-alt
                  Edit
            %h4.card-title Email Address Patterns
            - if @email_patterns.any?
              %ul
                - @email_patterns.each do |pattern|
                  %li
                    %code= pattern.pattern
            - else
              %p None

  #usage.tab-pane.fade{role: "tabpanel",
                       "aria-labelledby": "usage-tab"}
    .row
      .col-md-6
        .card
          .card-body
            %h4.card-title Units
            %h5 Allowed to administer
            - if @user_group.unit_administrator_groups.any?
              %ul
                - @user_group.unit_administrator_groups.each do |group|
                  %li= link_to(group.unit.title, group.unit)
            - else
              None
      .col-md-6
        .card
          .card-body
            %h4.card-title Collections
            %h5 Allowed to administer
            - if @user_group.collection_administrator_groups.any?
              %ul
                - @user_group.collection_administrator_groups.each do |group|
                  %li= link_to(group.collection.title, group.collection)
            - else
              None

            %h5 Allowed to submit
            - if @user_group.submitter_groups.any?
              %ul
                - @user_group.submitter_groups.each do |group|
                  %li= link_to(group.collection.title, group.collection)
            - else
              None
    .row
      .col-md-6
        .card
          .card-body
            %h4.card-title Items
            %h5 Allowed to download files
            - if @user_group.bitstream_authorizations.any?
              %ul
                - @user_group.bitstream_authorizations.each do |auth|
                  %li= link_to(auth.item.effective_title, auth.item)
            - else
              None

= render partial: "shared/xhr_modal",
         locals: { id: "edit-user-group-modal", title: "Edit User Group" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-ad-groups-modal", title: "Edit AD Groups" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-affiliations-modal", title: "Edit Affiliations" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-departments-modal", title: "Edit Departments" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-hosts-modal", title: "Edit Hosts" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-users-modal", title: "Edit Users" }
= render partial: "shared/xhr_modal",
         locals: { id: "edit-email-patterns-modal", title: "Edit Email Address Patterns" }