config/routes.rb
  # Health Check
  match "/health", to: "health#index", via: :get, as: "health"

  # Imports
  resources :imports do
    match "/complete-upload", to: "imports#complete_upload", via: :post
  end

  # Index Pages
  resources :index_pages, path: "index-pages"

  # Institutions
  resources :institutions, except: [:edit, :update], param: :key do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/access", to: "institutions#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/authentication", to: "institutions#show_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/buried-items", to: "institutions#show_buried_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/depositing", to: "institutions#show_depositing", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "institutions#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "institutions#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings/edit", to: "institutions#edit_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-agreement", to: "institutions#edit_deposit_agreement", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-help", to: "institutions#edit_deposit_help", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-questions", to: "institutions#edit_deposit_questions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-local-authentication", to: "institutions#edit_local_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-preservation", to: "institutions#edit_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "institutions#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-saml-authentication", to: "institutions#edit_saml_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-settings", to: "institutions#edit_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-theme", to: "institutions#edit_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings", to: "institutions#show_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-namespaces", to: "institutions#show_element_namespaces", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/elements", to: "institutions#show_element_registry", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/imports", to: "institutions#show_imports", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/index-pages", to: "institutions#show_index_pages", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/invitees", to: "institutions#show_invitees", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/metadata-profiles", to: "institutions#show_metadata_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/prebuilt-searches", to: "institutions#show_prebuilt_searches", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/preservation", to: "institutions#show_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/private-items", to: "institutions#show_private_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/properties", to: "institutions#show_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/rejected-items", to: "institutions#show_rejected_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/review-submissions", to: "institutions#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/settings", to: "institutions#show_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "institutions#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submission-profiles", to: "institutions#show_submission_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "institutions#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/supply-saml-configuration", to: "institutions#supply_saml_configuration", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/theme", to: "institutions#show_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/units", to: "institutions#show_units", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/usage", to: "institutions#show_usage", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/users", to: "institutions#show_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/user-groups", to: "institutions#show_user_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/vocabularies", to: "institutions#show_vocabularies", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/withdrawn-items", to: "institutions#show_withdrawn_items", via: :get,
          constraints: lambda { |request| request.xhr? }

    match "/banner-image", to: "institutions#remove_banner_image", via: :delete
    match "/deposit-agreement-questions", to: "institutions#update_deposit_agreement_questions", via: [:patch, :post]
    match "/empty-trash", to: "institutions#empty_trash", via: :post
    match "/favicon", to: "institutions#remove_favicon", via: :delete
    match "/footer-image", to: "institutions#remove_footer_image", via: :delete
    match "/generate-saml-cert", to: "institutions#generate_saml_cert", via: :patch
    match "/generate-saml-key", to: "institutions#generate_saml_key", via: :patch
    match "/header-image", to: "institutions#remove_header_image", via: :delete
    match "/item-download-counts", to: "institutions#item_download_counts", via: :get
    match "/preservation", to: "institutions#update_preservation", via: [:patch, :post]
    match "/properties", to: "institutions#update_properties", via: [:patch, :post]
    match "/refresh-saml-config-metadata", to: "institutions#refresh_saml_config_metadata", via: :patch
    match "/settings", to: "institutions#update_settings", via: [:patch, :post]
    match "/statistics-by-range", to: "institutions#statistics_by_range", via: :get
  end

  # Invitees
  match "/all-invitees", to: "invitees#index_all", via: :get, as: "all_invitees"
  match "/register", to: "invitees#register", via: :get
  resources :invitees, except: [:update] do
    collection do
      match "/create-unsolicited", to: "invitees#create_unsolicited", via: :post,
            as: "create_unsolicited"
    end
    match "/approve", to: "invitees#approve", via: [:patch, :post]
    match "/reject", to: "invitees#reject", via: [:patch, :post]
    match "/resend-email", to: "invitees#resend_email", via: [:patch, :post]
  end

  # Items
  resources :items, except: [:destroy, :index, :new] do
    collection do
      match "/export", to: "items#export", via: [:get, :post]
      match "/review", to: "items#review", via: :get
      match "/process_review", to: "items#process_review", via: :post
    end
    match "/approve", to: "items#approve", via: :patch
    resources :bitstreams do
      match "/data", to: "bitstreams#data", via: :get
      match "/ingest", to: "bitstreams#ingest", via: :post
      match "/object", to: "bitstreams#object", via: :get
      match "/viewer", to: "bitstreams#viewer", via: :get,
            constraints: lambda { |request| request.xhr? }
    end
    match "/bury", to: "items#bury", via: :post
    match "/download-counts", to: "items#download_counts", via: :get
    match "/exhume", to: "items#exhume", via: :post
    match "/edit-embargoes", to: "items#edit_embargoes", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-membership", to: "items#edit_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-metadata", to: "items#edit_metadata", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "items#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-withdrawal", to: "items#edit_withdrawal", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/file-navigator", to: "items#file_navigator", via: :get,
          constraints: lambda { |request| request.xhr? }
    # This supports links from file to file in HTML-format bitstreams within iframes.
    match "/files/:filename", to: "bitstreams#data", via: :get
    match "/reject", to: "items#reject", via: :patch
    match "/statistics", to: "items#statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/upload-bitstreams", to: "items#upload_bitstreams", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/withdraw", to: "items#withdraw", via: :patch
  end

  # Messages
  resources :messages, only: [:index, :show] do
    match "/resend", to: "messages#resend", via: :post
  end

app/controllers/invitees_controller.rb
# frozen_string_literal: true

##
# N.B.: see the documentation of {Invitee} for a detailed overview of the
# invitation & registration process.
#
class InviteesController < ApplicationController

  before_action :ensure_institution_host
  before_action :ensure_logged_in, except: [:create_unsolicited, :register]
  before_action :ensure_logged_out, only: [:create_unsolicited, :register]
  before_action :set_invitee, only: [:approve, :destroy, :edit, :reject,
                                     :resend_email, :show]
  before_action :authorize_invitee, only: [:approve, :destroy, :edit, :reject,
                                           :resend_email, :show]
  before_action :store_location, only: [:index, :index_all, :show]

  ##
  # Performs the opposite action as {reject}. Institution admins only.
  #
  # Responds to `PATCH/POST /invitees/:id/approve`.
  #
  def approve
    @invitee.approve
  rescue => e
    flash['error'] = "#{e}"
    redirect_back fallback_location: invitees_path
  else
    toast!(title:   "Invitee approved",
           message: "The invitee #{@invitee.email} has been approved, and "\
                    "will be receiving an email notification shortly.")
    redirect_back fallback_location: invitees_path
  end

  ##
  # Handles input from the invite-user form (institution admins only). This is
  # one of two entry points for invitees, the other being {create_unsolicited}.
  #
  # Responds to `POST /invitees`.
  #
  # @see create_unsolicited
  #
  def create
    @invitee               = Invitee.new(invitee_params)
    @invitee.institution ||= current_institution
    authorize(@invitee)
    begin
      ActiveRecord::Base.transaction do
        @invitee.save!
        @invitee.invite
      end
    rescue => e
      render partial: "shared/validation_messages",
             locals: { object: @invitee.errors.any? ? @invitee : e },
             status: :bad_request
    else
      toast!(title:   "Invitation sent",
             message: "An invitation has been sent to #{@invitee.email}.")
      render "shared/reload"
    end
  end

  ##
  # Handles input from the public account-request form. This is one of two
  # entry points for invitees, the other being {create}.
  #
  # Responds to `POST /invitees/create-unsolicited`.
  #
  # @see create
  #
  def create_unsolicited
    @invitee             = Invitee.new(invitee_params)
    @invitee.institution = current_institution
    authorize(@invitee)
    begin
      raise "Incorrect math question response. Please try again." unless check_captcha
      ActiveRecord::Base.transaction do
        @invitee.save!
        @invitee.send_reception_emails
      end
    rescue => e
      flash['error'] = "#{e}"
      redirect_to register_path
    else
      flash['success'] = "Thanks for requesting an account! We will review "\
          "your request and act on it as soon as possible. When we do, we'll "\
          "notify you via email."
      redirect_to @invitee.institution.scope_url,
                  allow_other_host: true # TODO: remove this and fix tests
    end
  end

  ##
  # Institution admins only.
  #
  # Responds to `DELETE /invitees/:id`.
  #
  def destroy
    @invitee.destroy!
  rescue => e
    flash['error'] = "#{e}"
  else
    toast!(title:   "Invitee deleted",
           message: "The invitee #{@invitee.email} has been deleted.")
  ensure
    redirect_back fallback_location: invitees_url
  end

  ##
  # N.B. contrary to its name, this method is used to render the
  # reject-an-invitee form, which is the only way an invitee would need to be
  # edited.
  #
  # Responds to `GET /invitees/:id/edit`
  #
  def edit
    render partial: "reject_form"
  end

  ##
  # Responds to `GET /invitees`
  #
  def index
    authorize(Invitee)
    setup_index(current_institution)
    respond_to do |format|
      format.html
      format.js { render partial: "invitees" }
    end
  end

  def index_all
    authorize(Invitee)
    setup_index(nil)
    respond_to do |format|
      format.html
      format.js { render partial: "all_invitees" }
    end
  end

  ##
  # Renders the invite-user form, which is only accessible by logged-in
  # institution admins. {create} handles the form submission.
  #
  # Responds to `GET /invitees/new`
  #
  # @see register
  #
  def new
    authorize Invitee
    if params.dig(:invitee, :institution_id).blank?
      render plain: "Missing institution ID", status: :bad_request
      return
    end
    @invitee            = Invitee.new(invitee_params)
    @invitee.expires_at = Time.zone.now + 1.year
    render partial: "new_form"
  end

  ##
  # The logged-out counterpart to {new} which renders the account-request form.
  # This is one of two pathways into the registration form, the other being an
  # invite from a sysadmin which goes to {new}. {create_unsolicited} handles
  # the form submission.
  #
  # Responds to `GET /invitees/register`
  #
  # @see new
  #
  def register
    @invitee = Invitee.new(expires_at: Time.zone.now + 1.year)
    authorize(@invitee)
  end

  ##
  # Performs the opposite action as {approve}. Institution admins only.
  #
  # Responds to `PATCH/POST /invitees/:id/reject`.
  #
  def reject
    reason = invitee_params[:rejection_reason] rescue nil
    @invitee.reject(reason: reason)
  rescue => e
    flash['error'] = "#{e}"
    redirect_back fallback_location: invitees_path
  else
    toast!(title:   "Invitee rejected",
           message: "The invitee #{@invitee.email} has been rejected and "\
                    "will be receiving an email notification shortly.")
    redirect_back fallback_location: invitees_path
  end

  ##
  # Institution admins only.
  #
  # Responds to `PATCH/POST /invitees/:id/resend-email`.
  #
  def resend_email
    @invitee.send_approval_email
  rescue => e
    flash['error'] = "#{e}"
    redirect_back fallback_location: invitees_path
  else
    toast!(title:   "Email re-sent",
           message: "An email has been sent to #{@invitee.email}.")
    redirect_to invitees_path
  end

  ##
  # Responds to `GET /invitees/:id`
  #
  def show
  end


  private

  def authorize_invitee
    @invitee ? authorize(@invitee) : skip_authorization
  end

  def invitee_params
    params.require(:invitee).permit(:email, :institution_admin,
                                    :institution_id, :inviting_user_id,
                                    :purpose, :rejection_reason)
  end

  def set_invitee
    @invitee = Invitee.find(params[:id] || params[:invitee_id])
    @breadcrumbable = @invitee
  end

  def setup_index(institution)
    @permitted_params = params.permit(Search::RESULTS_PARAMS +
                                        Search::SIMPLE_SEARCH_PARAMS +
                                        [:approval_state, :institution_id])
    @start            = [@permitted_params[:start].to_i.abs, max_start].min
    @window           = window_size
    @invitees         = Invitee.
      where("LOWER(email) LIKE ?", "%#{@permitted_params[:q]&.downcase}%").
      where(approval_state: @permitted_params[:approval_state] || Invitee::ApprovalState::PENDING).
      order(:created_at)
    if institution
      @invitees = @invitees.where(institution: institution)
    elsif params[:institution_id].present?
      @invitees = @invitees.where(institution_id: @permitted_params[:institution_id].to_i)
    end
    @count            = @invitees.count
    @invitees         = @invitees.limit(@window).offset(@start)
    @current_page     = ((@start / @window.to_f).ceil + 1 if @window > 0) || 1
    @new_invitee      = Invitee.new
  end

end

app/views/invitees/_actions_menu.html.haml
- if invitee.pending? || Rails.env.development?
  .dropdown
    %button.dropdown-toggle{type:             "button",
                            class:            button_class,
                            id:               "invitee-dropdown-#{invitee.id}",
                            "data-bs-toggle": "dropdown",
                            "aria-haspopup":  "true",
                            "aria-expanded":  "false"}
      Actions
    .dropdown-menu.dropdown-menu-right{"aria-labelledby": "invitee-dropdown-#{invitee.id}"}
      - if invitee.pending?
        = link_to(invitee_approve_path(invitee),
                  method: :patch,
                  class:  "dropdown-item",
                  data:   { confirm: "Are you sure you want to approve #{invitee.email}?\n\nThe invitee will be notified via email." }) do
          %i.fa.fa-check
          Approve
        = link_to(invitee_resend_email_path(invitee),
                  method: :patch,
                  class:  "dropdown-item",
                  data:   { confirm: "Are you sure you want to resend the invitation email?" }) do
          %i.fa.fa-envelope
          Resend Invitation Email
        %button.dropdown-item.reject{"data-invitee-id": invitee.id,
                                     "data-bs-target":  "#reject-modal",
                                     "data-bs-toggle":  "modal",
                                     role:              "button"}
          %i.fa.fa-times
          Reject

      - if Rails.env.development?
        %li
          %hr.dropdown-divider
        %h6.dropdown-header Testing Only
        = link_to(invitee_path(invitee),
                  method: :delete, class: "dropdown-item",
                  data: { confirm: "Are you sure you want to delete #{invitee.email}?\n\nNo notification will be sent." }) do
          = icon_for(:delete)
          Delete

app/views/invitees/_all_invitees.html.haml
- pagination = paginate(actual_count:     @count,
                        page:             @current_page,
                        per_page:         @window,
                        permitted_params: @permitted_params)

.row.justify-content-md-center
  .col-md-auto
    = pagination

%table.table
  %thead
    %tr
      %th Email
      %th Institution
      %th Invited By
      %th Approval State
      %th
  %tbody
    - @invitees.each do |invitee|
      %tr
        %td= link_to(invitee.email, invitee)
        %td= invitee.institution&.name
        %td= invitee.inviting_user ? link_to(invitee.inviting_user.name, invitee.inviting_user) : "Self-Invited"
        %td
          - case invitee.approval_state
          - when Invitee::ApprovalState::PENDING
            %span.badge.text-bg-primary PENDING
          - when Invitee::ApprovalState::APPROVED
            %span.badge.text-bg-success APPROVED
          - when Invitee::ApprovalState::REJECTED
            %span.badge.text-bg-danger REJECTED
        %td= render partial: "invitees/actions_menu",
                    locals: { invitee: invitee, button_class: "btn btn-sm btn-outline-secondary" }

.row.justify-content-md-center
  .col-md-auto
    = pagination

app/views/invitees/_filter_form.html.haml
.card.mb-3
  .card-body
    = form_tag invitees_path, method: :get, id: "invitees-form", class: "form-inline" do
      .row.mb-3
        .col
          = label_tag nil, "Email", class: "form-label"
          = filter_field
        .col
          = label_tag nil, "Approval State", class: "form-label"
          = select_tag "approval_state",
                       options_for_select(Invitee::ApprovalState::all.sort.map{ |s| [s.capitalize, s] },
                                          params[:approval_state] || Invitee::ApprovalState::PENDING),
                       class: "form-select"

app/views/invitees/_invitees.html.haml
- pagination = paginate(actual_count: @count, page: @current_page, per_page: @window,
                        permitted_params: @permitted_params)

.row.justify-content-md-center
  .col-md-auto
    = pagination

%table.table
  %thead
    %tr
      %th Email
      %th Invited By
      %th Date
      %th Approval State
      %th
  %tbody
    - @invitees.each do |invitee|
      %tr
        %td= link_to(invitee.email, invitee)
        %td= invitee.inviting_user ? link_to(invitee.inviting_user.name, invitee.inviting_user) : "Self-Invited"
        %td= local_time(invitee.created_at)
        %td
          - case invitee.approval_state
          - when Invitee::ApprovalState::PENDING
            %span.badge.text-bg-primary PENDING
          - when Invitee::ApprovalState::APPROVED
            %span.badge.text-bg-success APPROVED
          - when Invitee::ApprovalState::REJECTED
            %span.badge.text-bg-danger REJECTED
        %td= render partial: "invitees/actions_menu",
                    locals: { invitee: invitee, button_class: "btn btn-sm btn-outline-secondary" }

.row.justify-content-md-center
  .col-md-auto
    = pagination

app/views/invitees/_new_form.html.haml
= form_for(@invitee, url: invitees_path, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  = f.hidden_field :institution_id, value: f.object.institution_id
  = f.hidden_field :inviting_user_id, value: current_user.id
  = f.hidden_field :purpose, value: "Invited by #{current_user.name} (#{current_user.email})"

  - if f.object.institution.sso_enabled?
    .alert.alert-light
      %p
        = icon_for(:info)
        This form should only be used to invite users who are unable to log in
        via single sign-on (SSO). The invited user will be routed through the
        process to create an account with locally-stored credentials.

      %p.mb-0
        SSO users do not need to be invited. Their accounts are created
        automatically upon their first login.

  .mb-3
    = f.label :email, "Email", class: "required"
    = f.text_field :email, class: "form-control"
    %p.form-text
      = icon_for(:info)
      An email containing a link to the registration form will be sent
      to this address.

  .mb-3
    .form-check
      = f.check_box :institution_admin, class: "form-check-input"
      = f.label :institution_admin, "Make this user an administrator of #{f.object.institution.name}", class: "form-check-label"

  .mb-3
    = f.submit "Send Invite", class: "btn btn-primary"

app/views/invitees/_reject_form.html.haml
= form_for(@invitee, url: invitee_reject_path(@invitee)) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .mb-3
    = f.label :rejection_reason, "Reason", class: "form-label"
    = f.text_area :rejection_reason, class: "form-control"
    .form-text
      = icon_for(:info)
      If provided, this will be included in the email sent to the invitee.

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Reject Invitee", class: "btn btn-primary")

app/views/invitees/index.html.haml
- provide :body_id, "list_invitees"
- provide :title, "Invitees"

= hidden_field_tag :institution_id, current_institution.id

- if policy(User).invite?
  .btn-group.float-end{role: "group"}
    -# Invite button
    %button.add-invitee.btn.btn-light{"data-bs-target": "#add-invitee-modal",
                                      "data-bs-toggle": "modal",
                                      type:             "button"}
      %i.fa.fa-plus
      Invite User

%h1
  Invitees
  %small
    in
    = current_institution.name

= render partial: "filter_form"

#invitees-xhr-content
  = render partial: "invitees",
           locals: { count:            @count,
                     current_page:     @current_page,
                     invitees:         @invitees,
                     permitted_params: @permitted_params,
                     window:           @window }

= render partial: "shared/xhr_modal",
         locals: { id: "add-invitee-modal", title: "Invite User" }
= render partial: "shared/xhr_modal",
         locals: { id: "reject-modal", title: "Reject Invitee" }

app/views/invitees/index_all.html.haml
- provide :body_id, "list_invitees"
- provide :title, "Invitees"

%h1 All Invitees

.card.mb-3
  .card-body
    = form_tag all_invitees_path, method: :get, id: "invitees-form", class: "form-inline" do
      .row.mb-3
        .col
          = label_tag nil, "Email", class: "form-label"
          = filter_field
        .col
          = label_tag nil, "Institution", class: "form-label"
          = select_tag "institution_id",
                       options_for_select(Institution.order(:name).map{ |i| [i.name, i.id] },
                                          params[:institution_id]),
                       include_blank: true,
                       class: "form-select"
        .col
          = label_tag nil, "Approval State", class: "form-label"
          = select_tag "approval_state",
                       options_for_select(Invitee::ApprovalState::all.sort.map{ |s| [s.capitalize, s] },
                                          params[:approval_state] || Invitee::ApprovalState::PENDING),
                       class: "form-select"

#invitees-xhr-content
  = render partial: "all_invitees",
           locals: { count:            @count,
                     current_page:     @current_page,
                     invitees:         @invitees,
                     permitted_params: @permitted_params,
                     window:           @window }

= render partial: "shared/xhr_modal",
         locals: { id: "reject-modal", title: "Reject Invitee" }

app/views/invitees/new.html.haml
- provide :body_id, "account_request"
- provide :title, "Request an Account"

%h1 Request an Account

- if current_institution.key == "uiuc"
  .alert.alert-info.mb-3
    %p
      = icon_for(:info)
      In special circumstances, individuals who do not have an Illinois NetID are approved to register a non-NetID identity
      in the
      = current_institution.service_name
      system.
    %p
      %strong These non-NetID identities are not valid for access to items restricted to University of Illinois only or embargoed items.
    %p
      To request a non-NetID identity, provide your email address in the form below, along with the purpose.
      If approved, you will be sent an email inviting you to register.
    %p
      = current_institution.service_name
      administrators may be contacted at
      = succeed(".") do
        %a(href="mailto:#{current_institution.feedback_email}")
          = current_institution.feedback_email

= form_for(@invitee, url: create_unsolicited_invitees_path) do |f|
  .row.mb-3
    = f.label :email, class: "col-sm-3 col-form-label"
    .col-sm-9
      = f.text_field :email, class: "form-control", required: true
  .row.mb-3
    = f.label :note, "Purpose", class: "col-sm-3 col-form-label"
    .col-sm-9
      = f.text_area :note, class: "form-control", required: true

  - captcha_hash = captcha
  .row.mb-3
    = captcha_hash[:label]
    .col-sm-9
      = captcha_hash[:field]

  .row.mb-3
    .col-sm-3
    .col-sm-9
      = f.submit "Submit Request", class: "btn btn-primary"

app/views/invitees/register.html.haml
- provide :body_id, "account_request"
- provide :title, "Request an Account"

%h1 Request an Account

- if current_institution.key == "uiuc"
  .alert.alert-info.mb-3
    %p
      = icon_for(:info)
      In special circumstances, individuals who do not have an Illinois NetID are approved to register a non-NetID identity
      in the
      = current_institution.service_name
      system.
    %p
      %strong These non-NetID identities are not valid for access to items restricted to University of Illinois only or embargoed items.
    %p
      To request a non-NetID identity, provide your email address in the form below, along with the purpose.
      If approved, you will be sent an email inviting you to register.
    %p
      = current_institution.service_name
      administrators may be contacted at
      = succeed(".") do
        %a(href="mailto:#{current_institution.feedback_email}")
          = current_institution.feedback_email

= form_for(@invitee, url: create_unsolicited_invitees_path) do |f|
  .row.mb-3
    = f.label :email, class: "col-sm-3 col-form-label"
    .col-sm-9
      = f.text_field :email, class: "form-control", required: true
  .row.mb-3
    = f.label :purpose, "Purpose", class: "col-sm-3 col-form-label"
    .col-sm-9
      = f.text_area :purpose, class: "form-control", required: true

  - captcha_hash = captcha
  .row.mb-3
    = captcha_hash[:label]
    .col-sm-9
      = captcha_hash[:field]

  .row.mb-3
    .col-sm-3
    .col-sm-9
      = f.submit "Submit Request", class: "btn btn-primary"

app/views/invitees/show.html.haml
- provide :title, "Invitee #{@invitee.email}"

.btn-group.float-end{role: "group"}
  = render partial: "actions_menu", locals: { invitee: @invitee,
                                              button_class: "btn btn-light" }

%h1 Invitee #{@invitee.email}

%dl
  %dt Email
  %dd= link_to(@invitee.email, "mailto:#{@invitee.email}")
  %dt Associated User
  %dd= @invitee.user ? link_to(@invitee.user.name, @invitee.user) : "Not yet registered"
  %dt Invited By
  %dd= @invitee.inviting_user ? link_to(@invitee.inviting_user.name, @invitee.inviting_user) : "Self-Invited"
  %dt Institution Administrator
  %dd= boolean(@invitee.institution_admin, style: :word)
  %dt Purpose
  %dd= @invitee.purpose
  %dt Approval State
  %dd
    - case @invitee.approval_state
    - when Invitee::ApprovalState::PENDING
      %span.badge.text-bg-primary PENDING
    - when Invitee::ApprovalState::APPROVED
      %span.badge.text-bg-success APPROVED
    - when Invitee::ApprovalState::REJECTED
      %span.badge.text-bg-danger REJECTED
  %dt Created
  %dd= local_time_ago(@invitee.created_at)
  - if @invitee.pending? && @invitee.expires_at?
    %dt Expires
    %dd= local_time_ago(@invitee.expires_at)