config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "/", to: "welcome#index"

  # Authentication routes
  match "/auth/:provider/callback", to: "sessions#create", via: [:get, :post]
  match "/auth/failure", to: "sessions#auth_failed", as: :auth_failed, via: [:get, :post]
  match "/login", to: "sessions#new", as: :login, via: :get
  match "/logout", to: "sessions#destroy", as: :logout, via: :all

  # About
  match "/about", to: "welcome#about", via: :get, as: "about"

  # Collections
  resources :collections, except: :edit do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/about", to: "collections#show_about", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/access", to: "collections#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/all-files", to: "collections#all_files", via: :get
    match "/bury", to: "collections#bury", via: :post
    match "/exhume", to: "collections#exhume", via: :post
    match "/items", to: "collections#show_items", via: :get
    match "/review-submissions", to: "collections#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "collections#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "collections#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }

    match "/children", to: "collections#children", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "collections#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "collections#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-collection-membership",
          to: "collections#edit_collection_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "collections#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-groups", to: "collections#edit_submitting_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-submitting-users", to: "collections#edit_submitting_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-unit-membership", to: "collections#edit_unit_membership", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-results", to: "collections#item_results", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/item-download-counts", to: "collections#item_download_counts", via: :get
    match "/statistics-by-range", to: "collections#statistics_by_range", via: :get
    match "/submit", to: "submissions#new", via: :get
  end

  # Contact form
  match "/contact", to: "welcome#contact", via: :post,
        constraints: lambda { |request| request.xhr? }

  # Credentials
  resources :credentials, only: [:update] do
    match "/edit-password", to: "credentials#edit_password", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/register", to: "credentials#register", via: :get
    match "/reset-password", to: "credentials#new_password", via: :get
    match "/reset-password", to: "credentials#reset_password", via: [:patch, :post]
    match "/update-password", to: "credentials#update_password", via: [:patch, :post],
          constraints: lambda { |request| request.xhr? }
  end

  # Theme route
  match "/custom-styles", to: "stylesheets#show", via: :get

  # Downloads
  resources :downloads, only: :show, param: :key do
    match "/file", to: "downloads#file", via: :get, as: "file"
  end

  # Element Namespaces
  resources :element_namespaces, path: "element-namespaces", except: :show

  # Events
  match "/all-events", to: "events#index_all", via: :get, as: "all_events"
  resources :events, only: [:index, :show]

  # File Formats
  resources :file_formats, path: "file-formats", only: :index

  # Handle
  match "/handle/:prefix/:suffix", to: "handles#redirect", via: :get, as: "redirect_handle"

  # Health Check
  match "/health", to: "health#index", via: :get, as: "health"

  # Imports
  resources :imports do
    match "/complete-upload", to: "imports#complete_upload", via: :post
  end

  # Index Pages
  resources :index_pages, path: "index-pages"

  # Institutions
  resources :institutions, except: [:edit, :update], param: :key do
    # These all render content for the main tab panes in show-unit view via XHR.
    match "/access", to: "institutions#show_access", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/authentication", to: "institutions#show_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/buried-items", to: "institutions#show_buried_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/depositing", to: "institutions#show_depositing", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-groups", to: "institutions#edit_administering_groups", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-administering-users", to: "institutions#edit_administering_users", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings/edit", to: "institutions#edit_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-agreement", to: "institutions#edit_deposit_agreement", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-help", to: "institutions#edit_deposit_help", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-deposit-questions", to: "institutions#edit_deposit_questions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-local-authentication", to: "institutions#edit_local_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-preservation", to: "institutions#edit_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-properties", to: "institutions#edit_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-saml-authentication", to: "institutions#edit_saml_authentication", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-settings", to: "institutions#edit_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/edit-theme", to: "institutions#edit_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-mappings", to: "institutions#show_element_mappings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/element-namespaces", to: "institutions#show_element_namespaces", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/elements", to: "institutions#show_element_registry", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/imports", to: "institutions#show_imports", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/index-pages", to: "institutions#show_index_pages", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/invitees", to: "institutions#show_invitees", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/metadata-profiles", to: "institutions#show_metadata_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/prebuilt-searches", to: "institutions#show_prebuilt_searches", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/preservation", to: "institutions#show_preservation", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/private-items", to: "institutions#show_private_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/properties", to: "institutions#show_properties", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/rejected-items", to: "institutions#show_rejected_items", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/review-submissions", to: "institutions#show_review_submissions", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/settings", to: "institutions#show_settings", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/statistics", to: "institutions#show_statistics", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submission-profiles", to: "institutions#show_submission_profiles", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/submissions-in-progress", to: "institutions#show_submissions_in_progress", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/supply-saml-configuration", to: "institutions#supply_saml_configuration", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/theme", to: "institutions#show_theme", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/units", to: "institutions#show_units", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/usage", to: "institutions#show_usage", via: :get,
          constraints: lambda { |request| request.xhr? }
    match "/users", to: "institutions#show_users", via: :get,
          constraints: lambda { |request| request.xhr? }

app/models/embargo.rb
# frozen_string_literal: true

##
# Restricts {Item} access either perpetually or until a certain date,
# optionally exempting one or more {UserGroup}s.
#
# # Attributes
#
# * `created_at`    Managed by ActiveRecord.
# * `expires_at`    Date/time at which the embargo expires. For embargoes that
#                   never expire, {perpetual} is `true` and the value of this
#                   attribute is irrelevant.
# * `kind`          Value of one of the {Embargo::Kind} constants.
# * `item_id`       References the owning {Item}.
# * `perpetual`     Whether the embargo ever expires. If `true`, the embargo
#                   never expires and the value of {expires_at} is irrelevant.
# * `public_reason` Reason for the embargo which will be displayed in public.
# * `reason`        Reason for the embargo which will not be displayed in
#                   public.
# * `updated_at`    Managed by ActiveRecord.
#
# # Relationships
#
# * `item`        The owning {Item}.
# * `user_groups` Zero or more {UserGroup}s that are exempt from the embargo.
#
class Embargo < ApplicationRecord

  include Auditable

  scope :all_access, -> { where(kind: Kind::ALL_ACCESS) }
  scope :current, -> { where("perpetual = true OR expires_at > NOW()")}
  belongs_to :item, touch: true
  has_and_belongs_to_many :user_groups, -> { order(:name) }

  validates_inclusion_of :kind, in: -> (value) { Kind.all }

  validate :validate_expiration

  class IndexFields
    ALL_ACCESS_EXPIRES_AT = "d_all_access_expires_at"
    DOWNLOAD_EXPIRES_AT   = "d_download_expires_at"
    KIND                  = "i_kind"
  end

  class Kind
    # All access to the item via any means is restricted.
    ALL_ACCESS = 0
    # The item's bitstreams cannot be accessed.
    DOWNLOAD   = 1

    ##
    # @return [Enumerable<Integer>]
    #
    def self.all
      Kind.constants.map { |c| Kind.const_get(c) }
    end
  end

  def as_change_hash
    hash         = super
    hash['kind'] = Kind::constants.find{ |c| Kind.const_get(c) == self.kind }.to_s
    hash
  end

  ##
  # @return [Hash]
  #
  def as_indexed_json
    all_access_expires_at = nil
    download_expires_at   = nil
    case self.kind
    when Kind::ALL_ACCESS
      all_access_expires_at = (self.perpetual || !self.expires_at) ?
                                Time.now + 1000.years : self.expires_at
    when Kind::DOWNLOAD
      download_expires_at = (self.perpetual || !self.expires_at) ?
                              Time.now + 1000.years : self.expires_at
    end
    {
      IndexFields::ALL_ACCESS_EXPIRES_AT => all_access_expires_at&.iso8601,
      IndexFields::DOWNLOAD_EXPIRES_AT   => download_expires_at&.iso8601,
      IndexFields::KIND                  => self.kind
    }
  end

  ##
  # @param user [User]
  # @param client_ip [String]
  # @param client_hostname [String]
  # @return [Boolean] Whether the given user is exempt from the embargo.
  #
  def exempt?(user:, client_ip:, client_hostname:)
    self.user_groups.each do |group|
      return true if group.includes?(user:            user,
                                     client_ip:       client_ip,
                                     client_hostname: client_hostname)
    end
    false
  end


  private

  ##
  # Ensures that {expires_at} is not in the past.
  #
  def validate_expiration
    if !perpetual && expires_at && expires_at < Time.now
      errors.add(:expires_at, "must be in the future")
    end
  end

end

app/views/units/_access_form.html.haml
-# frozen_string_literal: true
-#
-# Required locals:
-#
-# unit [Unit]
-#
= form_for(unit, remote: true) do |f|
  .error-messages
    - # populated via ajax by shared/_validation_messages.js.erb

  / Include a random property because `unit` is required in the params
  = f.hidden_field :parent_id, value: f.object.parent_id

  - unless f.object.parent
    .form-group
      = label_tag :primary_administrator, "Primary Administrator"
      = text_field_tag :primary_administrator,
                       f.object.primary_administrator&.to_autocomplete,
                       autocomplete: "off",
                       class: "form-control"
      .dropdown-menu
        - # populated by javascript

  .form-group
    = label_tag "Administrators"
    = hidden_field_tag "administering_users[]"
    - user_strings = f.object.administering_users.each.map(&:to_autocomplete)
    - user_strings << user_strings[-1]
    - user_strings.each do |user_str|
      .input-group.mb-3.user
        = text_field_tag "administering_users[]", user_str,
                         autocomplete: "off",
                         class: "form-control"
        .input-group-append
          %button.btn.btn-outline-danger.remove{type: "button"}
            %i.fa.fa-minus
            Remove
        .dropdown-menu
          - # populated by javascript
    %button.btn.btn-sm.btn-outline-success.add
      %i.fa.fa-plus
      Add Administrator

  .clearfix
    .float-right
      %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
      = f.submit "Edit Unit", class: "btn btn-primary"

app/views/units/_administering_groups_form.html.haml
-# frozen_string_literal: true
-#
-# Required locals:
-#
-# unit [Unit]
-#
= form_for(unit, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  -# Include a random property because `unit` is required in the params
  = f.hidden_field :parent_id, value: f.object.parent_id

  = hidden_field_tag "user_group_ids[]"
  - UserGroup.where(institution: unit.institution).order(:name).each do |user_group|
    .form-check
      = check_box_tag "user_group_ids[]", user_group.id,
                      f.object.administrator_groups.where(user_group: user_group).any?,
                      { id: "user_group_ids_#{user_group.id}", class: "form-check-input" }
      = label_tag "user_group_ids_#{user_group.id}",
        user_group.name, class: "form-check-label"

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/units/_form.html.haml
-# frozen_string_literal: true
//
// Required locals:
//
// unit [Unit]
// context [Symbol] `:new` or `:edit`
//
= form_for(unit, remote: true) do |f|
  .error-messages
    - # populated via ajax by shared/_validation_messages.js.erb

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"

  .form-group
    = f.label :parent_id, "Parent Unit"
    = f.select(:parent_id,
        unit_tree_options_for_select(unit.parent, true),
        {}, { class: "custom-select" })

  - unless f.object.parent
    .form-group
      = label_tag :primary_administrator, "Primary Administrator"
      = text_field_tag :primary_administrator,
                       f.object.primary_administrator&.to_autocomplete,
                       autocomplete: "off",
                       class: "form-control"
      .dropdown-menu
        - # populated by javascript

  .form-group
    = label_tag "Administrators"
    = hidden_field_tag "administering_users[]"
    - user_strings = f.object.administering_users.each.map(&:to_autocomplete)
    - user_strings << user_strings[-1]
    - user_strings.each do |user_str|
      .input-group.mb-3.user
        = text_field_tag "administering_users[]", user_str,
                         autocomplete: "off",
                         class: "form-control"
        .input-group-append
          %button.btn.btn-danger.remove{type: "button"} &minus;
        .dropdown-menu
          - # populated by javascript
    %button.btn.btn-success.add &plus;

  .clearfix
    .float-right
      %button.btn.btn-light{"data-dismiss": "modal", type: "button"} Cancel
      = f.submit(context == :new ? 'Create Unit' : 'Edit Unit',
                 class: 'btn btn-primary')

app/views/units/_membership_form.html.haml
-# frozen_string_literal: true
-#
-# Required locals:
-#
-# unit [Unit]
-#
= form_for(unit, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .mb-3
    = f.label :parent_id, "Parent Unit"
    = f.select(:parent_id,
        options_for_select(unit_tree_options(institution:        f.object.institution,
                                             exclude_unit:       f.object,
                                             include_root:       true,
                                             include_only_admin: true),
        f.object.parent&.id),
        {}, { class: "form-select" })

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/units/_properties_form.html.haml
-# Required locals:
-#
-# unit [Unit]
-#
= form_for(unit, remote: true) do |f|
  .error-messages
    -# populated via ajax by shared/_validation_messages.js.erb

  .mb-3
    = f.label :title, class: "required"
    = f.text_field :title, class: "form-control"

  .mb-3
    = f.label :short_description, "Short Description"
    = f.text_area :short_description, class: "form-control"

  .mb-3
    = f.label :introduction
    = f.text_area :introduction, class: "form-control"
    %p.form-text
      = icon_for(:info)
      The following HTML tags are allowed:.
      = allowed_html_tags

  .mb-3
    = f.label :rights
    = f.text_area :rights, class: "form-control"

  .clearfix
    .float-end
      %button.btn.btn-light{"data-bs-dismiss": "modal", type: "button"} Cancel
      = f.submit("Save Changes", class: "btn btn-primary")

app/views/units/_show_about_tab.html.haml
.btn-group.float-end{role: "group"}
  - if policy(@unit).edit_properties?
    %button.btn.btn-light.edit-unit-properties{"data-unit-id":   @unit.id,
                                               "data-bs-target": "#edit-unit-properties-modal",
                                               "data-bs-toggle": "modal",
                                               role:             "button"}
      %i.fas.fa-pencil-alt
      Edit Properties

.clearfix.mb-3

%dl
  - if @unit.introduction.present?
    %dt Introduction
    %dd= raw(@unit.introduction)
  - if @unit.short_description.present? && policy(@unit).show_access?
    %dt Short Description
    %dd= @unit.short_description
  - if @unit.rights.present?
    %dt Rights
    %dd= @unit.rights
  %dt Handle URI
  %dd= @unit.handle&.permanent_url
  - if policy(@unit).show_extended_about?
    %dt File Downloads
    %dd= number_with_delimiter(@num_downloads)
    %dt Items Awaiting Review
    %dd= number_with_delimiter(@num_submitted_items)
    %dt Created
    %dd
      = local_time @unit.created_at
      - create_event = @unit.create_event
      - if create_event
        by
        = link_to(create_event.user) do
          = icon_for(create_event.user)
          = create_event.user.name
    %dt Last Updated
    %dd
      = local_time @unit.updated_at
      - update_event = @unit.last_update_event
      - if update_event
        by
        = link_to(update_event.user) do
          = icon_for(update_event.user)
          = update_event.user.name

%hr

.btn-group.float-end{role: "group"}
  - if policy(@unit).edit_membership?
    %button.btn.btn-light.edit-unit-membership{"data-unit-id":   @unit.id,
                                               "data-bs-target": "#edit-unit-membership-modal",
                                               "data-bs-toggle": "modal",
                                               role:             "button"}
      %i.fas.fa-pencil-alt
      Change Unit Membership
    %button.btn.btn-light.add-child-unit{"data-unit-id":   @unit.id,
                                         "data-bs-target": "#add-child-unit-modal",
                                         "data-bs-toggle": "modal",
                                         role:             "button"}
      %i.fa.fa-plus
      Add Child Unit

- if @unit.parent
  %h2 Parent Unit
  = resource_list([@unit.parent])

- if @subunits.any?
  %h2 Child Units
  = resource_list(@subunits)

- if !@unit.parent && @subunits.empty?
  %h2 Units
  %p This unit has no parent or sub-units.

%hr

= render partial: "show_collections_tab", locals: { show_title: true }

app/views/units/_show_downloads_by_item.html.haml
-# Content for the Statistics -> Downloads By Item tab

.float-end
  = link_to(unit_item_download_counts_path(@unit,
                                           format: :csv,
                                           params: params.permit(:from_year, :from_month, :to_year, :to_month)),
                                           class: "btn btn-light") do
    = icon_for(:download)
    CSV

%table.table
  %thead
    %tr
      %th Item
      %th Downloads
  %tbody
    - @items.each do |row|
      %tr
        %td= link_to(row['title'], item_path(row['id']))
        %td= number_with_delimiter(row['dl_count'])
    %tr
      %th Total
      %th= number_with_delimiter(@items.map{ |row| row['dl_count'] }.sum)

app/views/units/_show_downloads_tab_content.html.haml
%table.table
  %thead
    %tr
      %th Item
      %th Download Count
  %tbody
    - @items.each do |row|
      %tr
        %td= link_to(row['title'], item_path(row['id']))
        %td= number_with_delimiter(row['dl_count'])
    %tr
      %th Total
      %th= number_with_delimiter(@items.map{ |row| row['dl_count'] }.sum)

app/views/units/_show_membership_tab.html.haml
.btn-group.float-right{role: "group"}
  - if policy(@unit).edit_membership?
    %button.btn.btn-light.edit-unit-membership{"data-unit-id": @unit.id,
                                               "data-target": "#edit-unit-membership-modal",
                                               "data-toggle": "modal",
                                               role: "button"}
      %i.fas.fa-pencil-alt
      Change Unit Membership

- if !@unit.parent && @subunits.empty?
  .clearfix

- if @unit.parent
  %h2 Parent Unit
  = resource_list([@unit.parent])

- if @subunits.any?
  %h2 Child Units
  = resource_list(@subunits)

- if !@unit.parent && @subunits.empty?
  %p This unit has no parent or sub-units.

app/views/units/_show_statistics_by_month.html.haml
-# Content for the Statistics -> Statistics By Month tab

%ul.nav.nav-pills{role: "tablist"}
  %li.nav-item{role: "presentation"}
    %button#chart-tab.nav-link.active{"data-bs-toggle": "pill",
                                      "data-bs-target": "#chart-tab-content",
                                      role:             "tab",
                                      type:             "button",
                                      "aria-controls":  "chart-tab-content",
                                      "aria-selected":  "true"} Chart
  %li.nav-item{role: "presentation"}
    %button#table-tab.nav-link{"data-bs-toggle": "pill",
                               "data-bs-target": "#table-tab-content",
                               role:             "tab",
                               type:             "button",
                               "aria-controls":  "table-tab-content",
                               "aria-selected":  "false"} Table

.tab-content
  #chart-tab-content.tab-pane.fade.show.active{role: "tabpanel",
                                               "aria-labelledby": "chart-tab-content"}
    -# We will read this data on the client side in order to render the chart.
    = hidden_field_tag("chart-data", JSON.generate(@counts_by_month.to_a))
    %canvas#chart

  #table-tab-content.tab-pane.fade{role: "tabpanel",
                                   "aria-labelledby": "table-tab-content"}
    .float-end
      = link_to(unit_statistics_by_range_path(@unit,
                                              format: :csv,
                                              params: params.permit(:from_year, :from_month, :to_year, :to_month)),
                                              class: "btn btn-light") do
        = icon_for(:download)
        CSV

    %table.table
      %thead
        %tr
          %th Month
          %th Submitted Items
          %th Downloads
      %tbody
        - @counts_by_month.each do |row|
          %tr
            %td= row['month'].strftime("%B %Y")
            %td= number_with_delimiter(row['item_count'])
            %td= number_with_delimiter(row['dl_count'])
        %tr
          %th Total
          %th= number_with_delimiter(@counts_by_month.map{ |row| row['item_count'] }.sum)
          %th= number_with_delimiter(@counts_by_month.map{ |row| row['dl_count'] }.sum)

app/views/units/_show_statistics_tab.html.haml
#error-flash.alert.alert-danger{style: "display: none"}

= hidden_field_tag("chart_color", current_institution.primary_color)

.card.mb-3
  .card-body
    = form_tag("#", method: :get, class: "form-inline") do
      = date_range_picker

%ul.nav.nav-tabs{role: "tablist"}
  %li.nav-item{role: "presentation"}
    %button#statistics-by-month-tab.nav-link.active{"data-bs-toggle": "tab",
                                                    "data-bs-target": "#statistics-by-month-tab-content",
                                                    role:             "tab",
                                                    type:             "button",
                                                    "aria-controls":  "statistics-by-month-tab-content",
                                                    "aria-selected":  "true"} Statistics By Month

  %li.nav-item{role: "presentation"}
    %button#downloads-by-item-tab.nav-link{"data-bs-toggle": "tab",
                                           "data-bs-target": "#downloads-by-item-tab-content",
                                           role:             "tab",
                                           type:             "button",
                                           "aria-controls":  "downloads-by-item-tab-content",
                                           "aria-selected":  "false"} Downloads By Item

.tab-content
  #statistics-by-month-tab-content.tab-pane.fade.show.active{role: "tabpanel",
                                                             "aria-labelledby": "home-tab"}
    = spinner
  #downloads-by-item-tab-content.tab-pane.fade{role: "tabpanel",
                                               "aria-labelledby": "home-tab"}
    = spinner

app/views/units/create.js.erb
window.location = "<%= unit_path(unit) %>"

app/views/units/index.html.haml
- provide :body_id, "list_units"
- provide :title, "Academic Units"

= google_analytics_tags

= hidden_field_tag :institution_id, current_institution.id

-if policy(Unit).new?
  .btn-group.float-end{role: "group"}
    -# Add Unit button
    %button.btn.btn-light.add-unit{"data-bs-target": "#add-unit-modal",
                                   "data-bs-toggle": "modal",
                                   type:             "button"}
      %i.fa.fa-plus
      Add Unit

%h1 Academic Units and Collections

= expandable_unit_list(@units)

= render partial: "shared/xhr_modal",
         locals: { id: "add-unit-modal",
                   title: "Add Unit" }

app/views/units/show_buried.html.haml
- provide :body_id, "show_unit"
- provide :title, @unit.title

.btn-group.float-end{role: "group"}
  - if policy(@unit).exhume?
    = link_to(unit_exhume_path(@unit),
              class:          "btn btn-danger",
              method:         :post,
              "data-confirm": "Are you sure you want to undelete this unit?") do
      %i.fa.fa-trash-restore
      Undelete

.clearfix
.text-center
  %h1 410 Gone
  %hr
  %p This unit has been deleted.